services:
  api:
    image: api
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mongo

  frontend:
    image: movie-app
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - api

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
